# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd my-app
    npm install -g @angular/cli
    npm install
    echo "Current directory contents:"
    ls -al
    ng build --configuration development
    echo "Directory contents after ng build:"
    ls -al dist/my-app
  displayName: 'npm install and build'
  
- script: |
    echo "Contenu du répertoire de travail :"
    ls -R $(System.DefaultWorkingDirectory)
  displayName: 'Afficher le contenu du répertoire de travail'
  
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'dist'
    app_build_command: ng build --configuration development
    cwd: '$(System.DefaultWorkingDirectory)/my-app'
    azure_static_web_apps_api_token: $(token)
    deployment_environment: 'developpement'
    platform: 'node'
    runtime_version: '18.x'

